name: Other People
favicon: null
layout_spectrum: 0.18583632819354534
typography_spectrum: 0.5537385761272162
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.29059484228491783
  lightness: 0.07585043320432305
  saturation: 0.8355855245608836
  rhythmicContrast: 0.4153030060697347
purpose: []
